### ISSUE TITLE
Is the data available?

### ISSUE THREAD

**Issue by ielis** [institute-of-health-policies-sk/SIRmodel_COVID-19#1]
Dear institute members,
I would like to run your code within my environment, in order to play around with the model (I am not an expert though).
However, it seems that the folder `zdroje` is missing. Is there any way how to get access to the input data? Is the data public?

Thank you very much for your great work!
Cheers, Daniel

**Comment by gergelytakacs** [comment]
+1 here. It would make sense to share the data here. I think crowdsourcing the analysis is extremely useful at these times!

**Comment by milosmolnar** [comment]
There is a lot of parameters inside the model. Can you publish them, too?
From @institute-of-health-policies-sk document:
N – populácia v danej obci.
S – počet tých, ktorí sa môžu nakaziť (v simulácii všetci, ktorí nikdy nemali vírus)
I – počet infikovaných
R – počet vyliečených (v simulácii sa nemôžu nakaziť znovu)
x = I/ N – pomer infikovaných v obci
y = S / N – pomer tých, ktorí sa ešte môžu nakaziť (pomer „susceptible“)
m(j,k) – mobilita z obce j do obce
R0 – „basic reproduction number“, priemerný počet ľudí, ktorí sú nakazení infikovanou osobou.

**Comment by milosmolnar** [comment]
There is an important estimation in model (from ducument "_Mobilitu predikujeme na základe odborných (a agregovaných) odhadov, bez informácií od mobilných operátorov nevieme presne určiť migračné toky_")
Can you published this estimation, please?

**Comment by milosmolnar** [comment]
https://izp.sk/wp-content/uploads/2020/03/predikcia_koronavirus_17.3.2020_2.pdf

**Comment by misolietavec** [comment]
Without datafiles (mock, if you like) it is unusable. 
Bez dátových súborov (hoci aj oklieštených) je to nanič. Hovorí dlhoročný používateľ Pythonu
a IPython/Jupyter notebookov. Privítal by som dáta, aj kvôli demonštrácii modelu pre študentov.

**Comment by radovankavicky** [comment]
Same here... great work, but make your folders `/zdroje/` / `/zdroje int/` (+subfolders there) public (again)! :)

**Comment by radovankavicky** [comment]
Same here... great work, but make your folders `/zdroje/` / `/zdroje int/` (+subfolders there & all the data) public (again)! :)

**Comment by drhsub** [comment]
![image](https://user-images.githubusercontent.com/59415091/79402401-27a9eb00-7fa5-11ea-95dc-e0a4fa52d164.png)


1- I cant see these equations in the code
2- In code, looks like simple SIR model, I   =   beta_vec*SIR_sim[:, 0]*inflow_infected/(N_k + OD.sum(axis=0)) , but report shows different (see attached pic)
